# Generated by Django 5.2.9 on 2025-12-28 17:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_source', models.CharField(max_length=100)),
                ('id_source', models.IntegerField()),
                ('champ_concerne', models.CharField(max_length=100)),
                ('type_anomalie', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompagneAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.CharField(max_length=20)),
                ('jours', models.IntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Decoupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=100)),
                ('cod_provinc', models.CharField(max_length=10)),
                ('communes', models.CharField(max_length=100)),
                ('ccod_commun', models.CharField(max_length=10)),
                ('zones', models.CharField(max_length=100)),
                ('ccod_zones', models.CharField(max_length=10)),
                ('type_zone', models.CharField(max_length=50)),
                ('colqtr', models.CharField(max_length=100)),
                ('ccodcolqtr', models.CharField(max_length=20, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FicheFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheProvinciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mode_saisie', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('unite', models.CharField(max_length=50)),
                ('frequence', models.CharField(max_length=100)),
                ('formule_calcul', models.TextField()),
                ('source_donnees', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menage',
            fields=[
                ('id_mcd', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom_chef_menage', models.CharField(max_length=255)),
                ('prenom_c_m', models.CharField(max_length=255)),
                ('sexe_c_m', models.CharField(max_length=1)),
                ('statut_particulier', models.CharField(blank=True, max_length=100)),
                ('niveau_educa_chef', models.CharField(max_length=100)),
                ('statut_matrimonial', models.CharField(max_length=100)),
                ('taille_menage', models.IntegerField()),
                ('appartient_cooperative', models.BooleanField(default=False)),
                ('nom_cooperative', models.CharField(blank=True, max_length=255)),
                ('date_enquete', models.DateField()),
                ('nom_enqueteur', models.CharField(max_length=255)),
                ('source_saisie', models.CharField(max_length=100)),
                ('decoupage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.decoupage')),
            ],
        ),
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espece', models.CharField(max_length=100)),
                ('nb_animaux', models.FloatField()),
                ('revenu_2020', models.FloatField()),
                ('revenu_2025', models.FloatField()),
                ('raison_absence_betail', models.TextField(blank=True)),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.menage')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdam_score', models.IntegerField()),
                ('sca_score', models.FloatField()),
                ('nb_repas_saison_normale', models.IntegerField()),
                ('nb_repas_saison_soudure', models.IntegerField()),
                ('difficultes_alimentaires_12m', models.BooleanField()),
                ('frequence_difficultes', models.CharField(max_length=100)),
                ('mois_plus_difficiles', models.CharField(max_length=255)),
                ('chocs_5_derniers_ans', models.BooleanField()),
                ('type_chocs', models.CharField(max_length=255)),
                ('acces_eau_potable', models.BooleanField()),
                ('acces_soins_base', models.BooleanField()),
                ('distance_structure_sanitaire_km', models.FloatField()),
                ('menage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.menage')),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.compagneagricole')),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('valeur_calculee', models.FloatField()),
                ('valeur_cible', models.FloatField()),
                ('date', models.DateField()),
                ('methode_calcul', models.TextField()),
                ('decoupage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.decoupage')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.indicateur')),
            ],
        ),
    ]
