# Generated by Django 5.2.9 on 2025-12-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('decoupage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.decoupage')),
            ],
        ),
    ]
