# Generated by Django 5.2.9 on 2026-01-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_decoupage_ccod_commun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='type_anomalie',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='detecte_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='resolu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='severite',
            field=models.CharField(choices=[('critique', 'Critique'), ('importante', 'Importante'), ('mineure', 'Mineure')], default='mineure', max_length=20),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='status',
            field=models.CharField(choices=[('non_traite', 'Non traité'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='non_traite', max_length=20),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='type',
            field=models.CharField(choices=[('valeur_aberrante', 'Valeur aberrante'), ('doublon', 'Doublon'), ('incoherence', 'Incohérence logique'), ('manquant', 'Champ obligatoire manquant')], default='valeur_aberrante', max_length=50),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='valeur_actuelle',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='valeur_attendue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='champ_concerne',
            field=models.CharField(default='aucun', max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='id_source',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='table_source',
            field=models.CharField(default='inconnue', max_length=100),
        ),
        migrations.CreateModel(
            name='FluxSynchronisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('type_fiche', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], max_length=5)),
                ('nb_enregistrements', models.IntegerField()),
                ('status', models.CharField(default='en_attente', max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
