# Generated by Django 5.2.9 on 2026-01-02 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_anomalie_statut_remove_anomalie_type_anomalie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='resolu_le',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='valeur_attendue',
        ),
        migrations.RemoveField(
            model_name='consommation',
            name='sca_score',
        ),
        migrations.RemoveField(
            model_name='consommation',
            name='sdam_score',
        ),
        migrations.RemoveField(
            model_name='valeur',
            name='periode',
        ),
        migrations.AddField(
            model_name='menage',
            name='age_c_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menage',
            name='campagne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.compagneagricole'),
        ),
        migrations.AddField(
            model_name='menage',
            name='sca_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menage',
            name='sdam_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='valeur',
            name='saison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.saison'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='status',
            field=models.CharField(choices=[('non_traite', 'Non traité'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='non_traite', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type',
            field=models.CharField(choices=[('valeur_aberrante', 'Valeur aberrante'), ('doublon', 'Doublon'), ('incoherence', 'Incohérence logique'), ('manquant', 'Champ manquant')], default='valeur_aberrante', max_length=50),
        ),
        migrations.AlterField(
            model_name='compagneagricole',
            name='jours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='revenu_2020',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='revenu_2025',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fluxsynchronisation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='source_donnees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menage',
            name='date_enquete',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menage',
            name='nom_enqueteur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menage',
            name='prenom_c_m',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='menage',
            name='sexe_c_m',
            field=models.CharField(choices=[('H', 'H'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='menage',
            name='source_saisie',
            field=models.CharField(default='QField', max_length=100),
        ),
        migrations.AlterField(
            model_name='saison',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisons', to='analytics.compagneagricole'),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='methode_calcul',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='valeur_cible',
            field=models.FloatField(default=0),
        ),
    ]
