# Generated by Django 5.2.9 on 2025-12-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeurExte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('specification_qualite', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('jours_marche', models.CharField(max_length=100)),
                ('decoupage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.decoupage')),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('prix_vente_moyen', models.FloatField()),
                ('prix_min', models.FloatField()),
                ('prix_max', models.FloatField()),
                ('unite_prix', models.CharField(max_length=50)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.marche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut_offre', models.CharField(max_length=50)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.acteurexte')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recherchee', models.FloatField()),
                ('prix_souhaite', models.FloatField()),
                ('statut_demande', models.CharField(max_length=50)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.acteurexte')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.produit')),
            ],
        ),
    ]
