# Generated by Django 5.2.9 on 2025-12-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_prix', models.FloatField()),
                ('date_historique', models.DateField(auto_now_add=True)),
                ('prix_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri_market.prix')),
            ],
        ),
    ]
