# Generated by Django 5.2.9 on 2025-12-28 17:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('usg_parcelle', models.CharField(max_length=100)),
                ('secu_droit', models.CharField(max_length=100)),
                ('expl_comm', models.BooleanField()),
                ('int_comm', models.BooleanField()),
                ('voisin_nord', models.CharField(max_length=255)),
                ('voisin_sud', models.CharField(max_length=255)),
                ('voisin_est', models.CharField(max_length=255)),
                ('voisin_ouest', models.CharField(max_length=255)),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.menage')),
                ('phase_actuelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='foncier.phaseparcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('surface_culture_ha', models.FloatField()),
                ('quantite_produite_kg', models.FloatField()),
                ('quantite_stockee_kg', models.FloatField()),
                ('quantite_vendue_kg', models.FloatField()),
                ('quantite_autoconsommee_kg', models.FloatField()),
                ('prix_unitaire_fbukg', models.FloatField()),
                ('pourcentage_transforme', models.FloatField()),
                ('type_transformation', models.CharField(max_length=100)),
                ('specialisation_dominante', models.CharField(max_length=100)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foncier.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ConflitFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflit_foncier', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
                ('conflit_avec', models.CharField(max_length=255)),
                ('raison_conflit', models.TextField()),
                ('ans_conflit', models.IntegerField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foncier.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foncier.parcelle')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TitreFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_droit', models.BooleanField()),
                ('document', models.CharField(max_length=255)),
                ('num_demande', models.CharField(max_length=100)),
                ('date_de_demande', models.DateField()),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foncier.parcelle')),
            ],
        ),
    ]
