# Generated by Django 5.2.9 on 2026-01-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='est_securisee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='surface_culture_ha',
            field=models.FloatField(default=0.0),
        ),
    ]
