# Generated by Django 5.2.9 on 2026-01-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0002_parcelle_est_securisee_parcelle_surface_culture_ha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='expl_comm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='int_comm',
            field=models.BooleanField(default=False),
        ),
    ]
