# Generated by Django 5.2.9 on 2026-01-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_anomalie_resolu_le_and_more'),
        ('foncier', '0003_alter_parcelle_expl_comm_alter_parcelle_int_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='decoupage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.decoupage'),
        ),
    ]
