# Generated by Django 5.2.9 on 2026-01-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_journalaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('ressource_type', models.CharField(max_length=50)),
                ('ressource_id', models.CharField(max_length=50)),
                ('details', models.JSONField(null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Logs d'activité",
            },
        ),
    ]
